"""Erode or dilate the reference volume with niimath and re-mesh the result.

The glass-brain surface is regenerated by the pipeline

    niimath <reference> -erode <isolevel> <mm> -mesh -i <isolevel> -b 1 <out.gii>

Both morphology operators binarize at a threshold, so the threshold has to sit
on the same isosurface the mesh is extracted from; otherwise niimath shaves
voxels off the near-zero background and the visible surface never moves. The
isolevel niimath picks for the unmodified volume is therefore probed once and
reused for every offset.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from hashlib import sha1
from pathlib import Path
from typing import Any

NIIMATH_ENV_VAR = "TRACTFIGURE_NIIMATH"
NIIMATH_TIMEOUT_SECONDS = 600

# niimath reports the resolved isosurface twice: "isolevel=3.41159" in the
# option banner and "intensity range 0..15.4, isolevel 3.41159" in the log.
ISOLEVEL_PATTERN = re.compile(r"isolevel[=\s]\s*([-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?)")

VOLUME_SUFFIXES = (".gz", ".nii", ".hdr", ".img")


class NiimathError(RuntimeError):
    """niimath is unavailable, or it refused to process the reference volume."""


def find_niimath() -> Path | None:
    override = os.environ.get(NIIMATH_ENV_VAR, "").strip()

    if override:
        candidate = Path(override).expanduser()
        return candidate if candidate.is_file() else None

    # The niimath wheel installs its executable beside the interpreter, which is
    # not always on PATH when the viewer is launched from a virtual environment.
    for name in ("niimath", "niimath.exe"):
        candidate = Path(sys.executable).parent / name

        if candidate.is_file():
            return candidate

    discovered = shutil.which("niimath")
    return None if discovered is None else Path(discovered)


def offset_tag(millimeters: float) -> str:
    if millimeters > 0:
        return f"erode_{millimeters:g}mm"

    if millimeters < 0:
        return f"dilate_{abs(millimeters):g}mm"

    return "source"


def describe_offset(millimeters: float) -> str:
    if millimeters > 0:
        return f"eroded {millimeters:g} mm"

    if millimeters < 0:
        return f"diffused {abs(millimeters):g} mm"

    return "unmodified"


def _volume_stem(path: Path) -> str:
    stem = path.name

    for suffix in VOLUME_SUFFIXES:
        if stem.lower().endswith(suffix):
            stem = stem[: -len(suffix)]

    return stem or "volume"


def _source_digest(path: Path) -> str:
    status = path.stat()
    fingerprint = f"{path}|{status.st_size}|{status.st_mtime_ns}"
    return sha1(
        fingerprint.encode("utf-8"),
        usedforsecurity=False,
    ).hexdigest()[:8]


class SurfaceMorpher:
    """Cache of glass-brain surfaces generated at signed millimeter offsets."""

    def __init__(
        self,
        image_path: str | Path,
        cache_directory: str | Path,
        *,
        executable: str | Path | None = None,
        runner: Any | None = None,
    ) -> None:
        self.image_path = Path(image_path).expanduser().resolve()
        self.cache_directory = Path(cache_directory).expanduser().resolve()

        self._executable = None if executable is None else Path(executable)
        self._runner = self._run_niimath if runner is None else runner
        self._isolevel: float | None = None

    def _resolve_executable(self) -> Path:
        if self._executable is None:
            self._executable = find_niimath()

        if self._executable is None:
            raise NiimathError(
                "niimath was not found; install it with 'uv pip install niimath' "
                f"or point {NIIMATH_ENV_VAR} at the executable"
            )

        return self._executable

    def _run_niimath(self, arguments: list[str]) -> str:
        command = [str(self._resolve_executable()), *arguments]

        try:
            completed = subprocess.run(
                command,
                capture_output=True,
                text=True,
                timeout=NIIMATH_TIMEOUT_SECONDS,
                check=False,
            )
        except subprocess.TimeoutExpired as error:
            raise NiimathError(
                f"niimath did not finish within {NIIMATH_TIMEOUT_SECONDS} seconds"
            ) from error
        except OSError as error:
            raise NiimathError(f"niimath could not be executed: {error}") from error

        if completed.returncode != 0:
            reported = (completed.stderr or completed.stdout or "").strip().splitlines()
            detail = reported[-1] if reported else "no diagnostic output"
            raise NiimathError(f"niimath exited with code {completed.returncode}: {detail}")

        return f"{completed.stdout}\n{completed.stderr}"

    def _cache_directory(self) -> Path:
        directory_name = f"{_volume_stem(self.image_path)}-{_source_digest(self.image_path)}"
        return self.cache_directory / directory_name

    def _output_path(self, millimeters: float) -> Path:
        return self._cache_directory() / f"{offset_tag(millimeters)}.gii"

    def _isolevel_path(self) -> Path:
        return self._cache_directory() / "isolevel.txt"

    def _recorded_isolevel(self) -> float | None:
        recorded = self._isolevel_path()

        if not recorded.is_file():
            return None

        try:
            return float(recorded.read_text(encoding="utf-8").strip())
        except (OSError, ValueError):
            return None

    def _record_isolevel(self, output: str) -> None:
        match = ISOLEVEL_PATTERN.search(output)

        if match is None:
            return

        self._isolevel = float(match.group(1))
        self._isolevel_path().write_text(
            f"{self._isolevel:.10g}\n",
            encoding="utf-8",
        )

    def isosurface_level(self) -> float:
        """Isovalue niimath extracts the unmodified surface at."""

        if self._isolevel is None:
            self._isolevel = self._recorded_isolevel()

        if self._isolevel is None:
            self._generate(0.0)

        if self._isolevel is None:
            raise NiimathError("niimath did not report the isosurface level it used")

        return self._isolevel

    def mesh_for_offset(self, millimeters: float) -> Path:
        """Surface for `millimeters` of erosion (positive) or diffusion (negative)."""

        output_path = self._output_path(millimeters)

        if output_path.is_file():
            return output_path

        return self._generate(millimeters)

    def _generate(self, millimeters: float) -> Path:
        output_path = self._output_path(millimeters)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        arguments = [str(self.image_path)]

        if millimeters:
            isolevel = f"{self.isosurface_level():g}"
            arguments += [
                "-erode" if millimeters > 0 else "-dilate",
                isolevel,
                f"{abs(millimeters):g}",
                "-mesh",
                "-i",
                isolevel,
            ]
        else:
            arguments.append("-mesh")

        arguments += ["-b", "1", str(output_path)]

        output = self._runner(arguments)

        if not millimeters:
            self._record_isolevel(output)

        if not output_path.is_file():
            raise NiimathError(f"niimath did not write the surface: {output_path.name}")

        return output_path
