"""Erode or dilate the reference volume with niimath and re-mesh the result.

The glass-brain surface is regenerated by the pipeline

    niimath <reference> -erode <isolevel> <mm> -mesh -i <isolevel> -b 1 <out.gii>

Both morphology operators binarize at a threshold, so the threshold has to sit
on the same isosurface the mesh is extracted from; otherwise niimath shaves
voxels off the near-zero background and the visible surface never moves. The
isolevel niimath picks for the unmodified volume is therefore probed once and
reused for every offset.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from collections.abc import Callable
from hashlib import sha1
from pathlib import Path

NIIMATH_ENV_VAR = "TRACTFIGURE_NIIMATH"
NIIMATH_TIMEOUT_SECONDS = 600

# niimath reports the resolved isosurface twice: "isolevel=3.41159" in the
# option banner and "intensity range 0..15.4, isolevel 3.41159" in the log.
ISOLEVEL_PATTERN = re.compile(r"isolevel[=\s]\s*([-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?)")


class NiimathError(RuntimeError):
    """niimath is unavailable, or it refused to process the reference volume."""


def find_niimath() -> Path | None:
    override = os.environ.get(NIIMATH_ENV_VAR, "").strip()

    if override:
        candidate = Path(override).expanduser()
        return candidate if candidate.is_file() else None

    # The niimath wheel installs its executable beside the interpreter, which is
    # not always on PATH when the viewer is launched from a virtual environment.
    for name in ("niimath", "niimath.exe"):
        candidate = Path(sys.executable).parent / name

        if candidate.is_file():
            return candidate

    discovered = shutil.which("niimath")
    return None if discovered is None else Path(discovered)


def offset_tag(millimeters: float) -> str:
    if millimeters > 0:
        return f"erode_{millimeters:g}mm"

    if millimeters < 0:
        return f"dilate_{abs(millimeters):g}mm"

    return "source"


def describe_offset(millimeters: float) -> str:
    if millimeters > 0:
        return f"eroded {millimeters:g} mm"

    if millimeters < 0:
        return f"diffused {abs(millimeters):g} mm"

    return "unmodified"


def _source_digest(path: Path) -> str:
    """Identify one revision of one volume, so a swapped reference misses the cache."""

    status = path.stat()
    fingerprint = f"{path}|{status.st_size}|{status.st_mtime_ns}"
    return sha1(
        fingerprint.encode("utf-8"),
        usedforsecurity=False,
    ).hexdigest()[:8]


class SurfaceMorpher:
    """Cache of glass-brain surfaces generated at signed millimeter offsets."""

    def __init__(
        self,
        image_path: str | Path,
        cache_directory: str | Path,
        *,
        runner: Callable[[list[str]], str] | None = None,
    ) -> None:
        self.image_path = Path(image_path).expanduser().resolve()
        self.cache_directory = Path(cache_directory).expanduser().resolve()

        self._runner = self._run_niimath if runner is None else runner
        self._isolevel: float | None = None

    def _run_niimath(self, arguments: list[str]) -> str:
        executable = find_niimath()

        if executable is None:
            raise NiimathError(
                "niimath was not found; install it with 'uv pip install niimath' "
                f"or point {NIIMATH_ENV_VAR} at the executable"
            )

        try:
            completed = subprocess.run(
                [str(executable), *arguments],
                capture_output=True,
                text=True,
                timeout=NIIMATH_TIMEOUT_SECONDS,
                check=False,
            )
        except subprocess.TimeoutExpired as error:
            raise NiimathError(
                f"niimath did not finish within {NIIMATH_TIMEOUT_SECONDS} seconds"
            ) from error
        except OSError as error:
            raise NiimathError(f"niimath could not be executed: {error}") from error

        if completed.returncode != 0:
            reported = (completed.stderr or completed.stdout or "").strip().splitlines()
            detail = reported[-1] if reported else "no diagnostic output"
            raise NiimathError(f"niimath exited with code {completed.returncode}: {detail}")

        return f"{completed.stdout}\n{completed.stderr}"

    def _output_path(self, millimeters: float) -> Path:
        digest = _source_digest(self.image_path)
        return self.cache_directory / f"{digest}_{offset_tag(millimeters)}.gii"

    def isosurface_level(self) -> float:
        """Isovalue niimath extracts the unmodified surface at."""

        if self._isolevel is None:
            self._generate(0.0)

        if self._isolevel is None:
            raise NiimathError("niimath did not report the isosurface level it used")

        return self._isolevel

    def mesh_for_offset(self, millimeters: float) -> Path:
        """Surface for `millimeters` of erosion (positive) or diffusion (negative)."""

        output_path = self._output_path(millimeters)

        if output_path.is_file():
            return output_path

        return self._generate(millimeters)

    def _generate(self, millimeters: float) -> Path:
        output_path = self._output_path(millimeters)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        arguments = [str(self.image_path)]

        if millimeters:
            isolevel = f"{self.isosurface_level():g}"
            arguments += [
                "-erode" if millimeters > 0 else "-dilate",
                isolevel,
                f"{abs(millimeters):g}",
                "-mesh",
                "-i",
                isolevel,
            ]
        else:
            arguments.append("-mesh")

        arguments += ["-b", "1", str(output_path)]

        output = self._runner(arguments)

        if not millimeters:
            match = ISOLEVEL_PATTERN.search(output)

            if match is not None:
                self._isolevel = float(match.group(1))

        if not output_path.is_file():
            raise NiimathError(f"niimath did not write the surface: {output_path.name}")

        return output_path
